name: Check RSS and Notify

on:
  schedule:
    - cron: '*/1080 * * * *'  # 每 1080 分钟运行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  check_rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check Python and pip versions
        run: |
          python --version
          pip --version  # 查看 Python 和 pip 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # 升级 pip
          pip install requests feedparser plyer  # 安装依赖库

      - name: Run Python script
        run: |
          python js.py  # 使用 python 命令来运行脚本
